baseURL = "https://example.com/"
languageCode = "en-us"
title = "Christian Walker"
theme = "hugo-resume"
publishDir = "dist"

[params]
    firstName = "Christian"
    lastName = "Walker"
    address = "Allegheny College  "
    contactNote = "Entrepreneur"
    profileImage = "img/TechChat.png"
    email = "walkerc3@allegheny.edu"
    description = "God first. College Student. Entrepreneur."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/cdwalkers/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dubswalker/PanelCV"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "key"

[params.google.analytics]
    trackerID = "XX-123446-01"
